#! /bin/bash
# yak rover name is set in /etc/environment
if [[ -z "${YAK_ROVER_NAME}" ]]; then
    export $YAK_ROVER_NAME=iamz1
fi

sed s/\"iamz1\"/\"$YAK_ROVER_NAME\"/ runonbot.html >streamit.html

timeout $1 chromium-browser --headless --disable-gpu --use-fake-ui-for-media-stream --remote-debugging-port=9222 streamit.html &
echo you can kill by kill -9 $(ps ax | grep 'streamit' | awk '{printf $1 " "}')
echo kill -9 $(ps ax | grep 'streamit' | awk '{printf $1 " "}') >stopvideo

